name: Run Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit count as build number
        run: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          echo "Build number (commit count): $BUILD_NUMBER"
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Build project
        run: |
          echo "Building project..."
          echo "Build number: $BUILD_NUMBER"

  send-cdd-notification-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Build Notification to CDD
        env:
        
          CDDIRECTOR_IO_BASE: ${{ secrets.CDDIRECTOR_IO_BASE }}
        run: |
          curl -X POST "https://cddirector.io/cdd/design/dd956bb5-1be0-4855-8606-c515c7926e0c/v1/applications/application-versions/application-version-builds" \
            -H "Authorization: Bearer $CDDIRECTOR_IO_BASE" \
            -H "Content-Type: application/json" \
            -d '{
                  "applicationName": "APP 1",
                  "applicationVersionBuildNumber": "$GITHUB_RUN_ID",
                  "applicationVersionName": "master"
                }'
