name: Trigger Ansible Tower Job

on:
  push:
    branches:
      - main

jobs:
  trigger-tower-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Build Notification to CDD
        env:
        
          CDDIRECTOR_IO_BASE: ${{ secrets.CDDIRECTOR_IO_BASE }}
        run: |
          curl -X POST "https://cddirector.io/cdd/design/dd956bb5-1be0-4855-8606-c515c7926e0c/v1/applications/application-versions/application-version-builds" \
            -H "Authorization: Bearer $CDDIRECTOR_IO_BASE" \
            -H "Content-Type: application/json" \
            -d '{
                  "applicationName": "APP 1",
                  "applicationVersionBuildNumber": "2",
                  "applicationVersionName": "master"
                }'
